services:
  db:
    image: postgres:alpine
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example_password}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal-bridge

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-frontend
    stdin_open: true
    tty: true
    networks:
      - internal-bridge
      - web-gateway
    depends_on:
      - api-server

  api-server:
    build: ./backend
    container_name: ${PROJECT_NAME}-api-server
    environment:
      - DATABASE_URL=postgres://${DB_USER:-myuser}:${DB_PASSWORD:-example_password}@${PROJECT_NAME}-db:5432/${DB_NAME:-mydatabase}
    networks:
      - internal-bridge
      - web-gateway
    depends_on:
      - db

networks:
  internal-bridge:
    driver: bridge
  web-gateway:
    external: true # Changed from external: true for local standalone testing

volumes:
  db_data:
